-- Supabase persistence migration for SOMA personal fitness journal.
-- Adds durable storage for templates, measurement logs, calendar entries,
-- and user preferences so data survives PWA reinstalls and device changes.

-- ─── 1. workout_templates ────────────────────────────────────────────────────
-- Change id to text so the app's existing 'template-<timestamp>' IDs can be
-- stored without casting. New rows generated by the app use crypto.randomUUID().
ALTER TABLE public.workout_templates ALTER COLUMN id TYPE text;

-- Add columns that the app stores in WorkoutTemplate but weren't in the schema.
ALTER TABLE public.workout_templates
  ADD COLUMN IF NOT EXISTS default_duration_minutes integer,
  ADD COLUMN IF NOT EXISTS exercises jsonb NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS activity_details jsonb NOT NULL DEFAULT '[]';

CREATE INDEX IF NOT EXISTS idx_workout_templates_user_updated
  ON public.workout_templates (user_id, updated_at DESC);

-- ─── 2. measurement_logs ─────────────────────────────────────────────────────
-- Text + user_id composite PK accepts 'weight-<timestamp>' / 'measure-<timestamp>'
-- IDs already living in localStorage. RLS scopes each row to the owning user.
CREATE TABLE IF NOT EXISTS public.measurement_logs (
  id          text        NOT NULL,
  user_id     uuid        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  logged_date date        NOT NULL,
  values      jsonb       NOT NULL DEFAULT '{}',
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, id)
);
ALTER TABLE public.measurement_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage own measurement logs" ON public.measurement_logs
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE INDEX IF NOT EXISTS idx_measurement_logs_user_date
  ON public.measurement_logs (user_id, logged_date DESC);

-- ─── 3. calendar_entries ─────────────────────────────────────────────────────
-- Stores each CalendarEntry (workout, note, weight, photo, etc.) as a jsonb
-- payload keyed by (user_id, id). Text id accepts 'workoutLog-<ts>' style IDs.
CREATE TABLE IF NOT EXISTS public.calendar_entries (
  id          text        NOT NULL,
  user_id     uuid        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  entry_date  date        NOT NULL,
  entry_type  text        NOT NULL,
  payload     jsonb       NOT NULL DEFAULT '{}',
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, id)
);
ALTER TABLE public.calendar_entries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage own calendar entries" ON public.calendar_entries
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE INDEX IF NOT EXISTS idx_calendar_entries_user_date
  ON public.calendar_entries (user_id, entry_date DESC);

-- ─── 4. user_journal_preferences ─────────────────────────────────────────────
ALTER TABLE public.user_journal_preferences
  ADD COLUMN IF NOT EXISTS habit_rows             jsonb       NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS custom_tags            text[]      NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS track_strength_weights boolean     NOT NULL DEFAULT true;

-- ─── 5. profiles preference columns ──────────────────────────────────────────
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS theme                text    NOT NULL DEFAULT 'dark',
  ADD COLUMN IF NOT EXISTS units                text    NOT NULL DEFAULT 'lbs',
  ADD COLUMN IF NOT EXISTS onboarding_completed boolean NOT NULL DEFAULT false;
